# Generated by Django 5.1 on 2024-08-13 05:56

import hotels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to=hotels.models.hotel_image_file_path),
        ),
    ]
